name: Python Tests

on:
  push:
    branches:
      - main  # Runs tests when you push to the main branch
  pull_request:
    branches:
      - main  # Runs tests on PRs targeting the main branch
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can change this to your required Python version

      # Install pytest directly
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
